language: elixir
  
elixir:
  - 1.2

otp_release:
  - 18.0

sudo: false

cache:
  - directories:
      - _build
      - deps 

before_script:
  - psql -c 'create database todox_test;' -U postgres

script:
  - mix test

services:
  - postgresql

notifications:
  email:
    on_sucess: never
    on_failure: always

